### ISSUE TITLE
Thoughts on where I can help

### ISSUE THREAD

**Issue by rtorr** [raphamorim/react-ape#1]
I work on UI for the PS4 daily, so I have some investment in this type of work, and over the past year, I have implemented a lot of the ideas here. So if it is welcome, I am going to use this issue to jot down some ideas (some i'm sure you have planned), and see if I can help in any way.

You are probably busy in the weeds for the reconciler. 

Things I have implemented that I could maybe bring over:

* `ListView`
* `ScrollableView`
* `FocusSystem` (gamepad for example)
* Positioning based on parent.
* Improvements to the `Image` component, for example pre-loaded state, post-loaded, error, and caching.
* Accessibility
* Animation

Another huge win would be to implement flexbox https://github.com/facebook/yoga 

Above all of this, I have a ps4 devkit that I can help test on.

Let me know if you need/want help, and if it is too early, I can check back later.

**Comment by raphamorim** [comment]
Definitely @rtorr I want your help with it! :octocat: 📺 

Sorry for delay! I was coming back from a trip, now I'm back to work on it. Once it's clear which is the best "abstraction" to ReactElements based on canvas/webgl. We can work together in new Primitives and Elements.

**Comment by junior201110** [comment]
Brow I've Bernardo workshop with React since 2014. How can I help you ? I look for your project and I loved it.

**Comment by dead** [comment]
If you want a flexbox implementation, have a look at this: https://github.com/dead/typeflex 😄 
It is basically a Yoga port in typescript.

**Comment by raphamorim** [comment]
@dead what's the difference between yoga? I've created this ticket https://github.com/raphamorim/react-ape/issues/42. I'm considering using some lib or even yoga to deal with that.

`Positioning based on parent`, `ListView`, `ScrollableView` and `accessibility` are topics that I definitely need some help. I mean, all the help is welcome 🙏. Closing this issue. :shipit:
