### ISSUE TITLE
ListView

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-ape#10]
- [x] Create ListView Component
- [ ] ListView Scroll Horizontal
- [ ] ListView Scroll Vertical
- [ ] Automatically distribute items coordinates based on width/height of each child

**Comment by ahmad2smile** [comment]
There is no setup for vertical or horizontal options on List. I'm really interested how you gonna implement scroll on list with mouse/pad scroll. I did sort of a hack for it but Its not much of solution as you need a large html div container where native browser scrollbars would be.

My implementation: https://github.com/ahmad2smile/react-canvas-list

**Comment by raphamorim** [comment]
Closing in favour of #33 since ListView is being deprecated by RN
