### ISSUE TITLE
react ape roadmap and future

### ISSUE THREAD

**Issue by daniloab** [raphamorim/react-ape#110]
Hi, @raphamorim 

This project looks really cool and I want to help it also to develop and learn.

- are you thinking about in a roadmap? like review the already done things and update?
- is the react functional components features inside of the roadmap?
- bonus: fix the roadmap hyperlink on docs
![image](https://user-images.githubusercontent.com/19939822/156276922-d1fee5c6-747c-4afd-ba82-2c3a0752849a.png)

**Comment by raphamorim** [comment]
I believe that good issues to start are https://github.com/raphamorim/react-ape/issues/43 and https://github.com/raphamorim/react-ape/issues/19
