### ISSUE TITLE
Unable to accept Discord invite

### ISSUE THREAD

**Issue by scald** [raphamorim/react-ape#130]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1215913/180067170-a0cd39fa-6cf2-481b-87c9-464d319c39c5.png">

Link: https://discord.com/invite/njHHfRzJ42

**Comment by raphamorim** [comment]
Hey @scald thanks for the issue, can you try with https://discord.gg/D6JwqQJQ ?

**Comment by scald** [comment]
Worked!
