### ISSUE TITLE
Could We create an app for adding elements on Canvas using drag-and-drop?

### ISSUE THREAD

**Issue by afgoulart** [raphamorim/react-ape#137]
I have a project to create a canvas by inserting many elements using drag-and-drop, and I'll likely use this project to manipulate canvas elements.

Another question: The React-Ape has animation effects or filters for elements?

**Comment by raphamorim** [comment]
Hey there @afgoulart 👋 

> I have a project to create a canvas by inserting many elements using drag-and-drop, and I'll likely use this project to manipulate canvas elements.

Feel free to use it but ReactApe could be unstable depending of what you are planning to use. Please let me know if you run into any issues.

> Another question: The React-Ape has animation effects or filters for elements?

Currently not 😢

**Comment by afgoulart** [comment]
Thanks, man! Can We talk about this issue so I can contribute to this project?
