### ISSUE TITLE
It's time to start the documentation

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-ape#16]
I was thinking about using https://docusaurus.io/ in `docs/` folder. Following the structure of [react-native](https://facebook.github.io/react-native/docs/getting-started) (e.g: `The Basics`, `Guides`,  `Components`, `APIs`). 

I'm very open to other ideas too.

**Comment by pedronauck** [comment]
Maybe you can give a little look at https://github.com/pedronauck/docz ✌️

**Comment by raphamorim** [comment]
Seems a good option @pedronauck! Do will work with custom renderers (rendering in canvas)?

**Comment by pedronauck** [comment]
I think not @raphamorim, by now we just render components on the fly using the `<Playground>` component, so what you can do is create your own renderer and render on `<Playground`>, I don't know but I think that can works:

```
<Playground>
  <Canvas>
    {/* some stuff */}
  </Canvas>
</Playground>
```

But, this is a pretty good idea, I'll think about that and maybe add on our roadmap 🙏

**Comment by pedronauck** [comment]
Another good solution that you can use is something like Runkit @raphamorim, I did see it now, is pretty awesome and easy to use inside docz. I'm thinking to create some component to use it in an easy way.
https://runkit.com/
