### ISSUE TITLE
Support for life-cycle events on Renderer elements

### ISSUE THREAD

**Issue by djunior** [raphamorim/react-ape#17]
Please add support for life-cycle events to basic Renderer elements such as:
* componentDidMount
* componentWillUnmount
* componentDidUpdate

I currently work with a fps-based rendering engine operating on canvas, and I wanted to try implementing those elements based on the existing Components on this engine.

**Comment by raphamorim** [comment]
For the initial release, gonna focus on custom components using classes with render and reset methods which can be called by React Ape. It's gonna improve over time (adding more lifecycles and making it more similar to a React Component class)

https://raphamorim.io/react-ape/docs/customcomponents-registercomponent
