### ISSUE TITLE
[Spectrum Request] - It would be a good idea to have a community

### ISSUE THREAD

**Issue by YobertyAlej** [raphamorim/react-ape#30]
I've check your project and it seems really cool and ambitious to me, the idea of canvas as a "**rendering engine**" can have many advantages and use cases (personally i'll love to dig into **PS4 UI** dev), i'm pretty sure there's a lot of more people who would be interested in contributing.

However it would be great if these people could find a way to communicate, that's why i'm suggesting a **spectrum community**

Cheers, and never stop doing it! 🔥

**Comment by raphamorim** [comment]
Hi @YobertyAlej! Yes, it's a good idea. Any specific reason for spectrum? Why not slack or discord?

**Comment by YobertyAlej** [comment]
**IMO** spectrum offers better support for the idea of a community, slack get a little tedious and not everyone will be interested in joining, spectrum seems a little bit more "casual" to me, thus people can just check the project and it's discussions without the need for joining, if they get interested then they can sign in

**Comment by YobertyAlej** [comment]
Closing

**Comment by raphamorim** [comment]
Hi @YobertyAlej. Sorry the delay. I think it's a great idea, I confess that I'm the worst person to log into Slack, Discord, Spectrum and etecetera. I'll see which one fits better and update here. :)

**Comment by matheusmonte** [comment]
@raphamorim if you need some help in this, I can help to try to answer community questions
