### ISSUE TITLE
Render?build in ARM architecture

### ISSUE THREAD

**Issue by iagocavalcante** [raphamorim/react-ape#6]
It's possible to build and run for ARM architecure, i would like to build some things to run in raspberry with this.

**Comment by raphamorim** [comment]
With a browser running on ARM raspberry should be possible to render using Ape. Highly recommend selecting a browser based on your raspberry config.

**Comment by raphamorim** [comment]
I'm closing this issue, any other issue on it we can open another :octocat:  :)
